import{a as S,S as w,i as m}from"./assets/vendor-06b1bbdf.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();async function f(r,o,n){try{const s="42024846-08e8117282465e780d398d927",e="https://pixabay.com/api/",t=new URLSearchParams({key:s,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:n,page:o});return(await S.get(`${e}?${t}`)).data}catch(s){console.log(s)}}const d=document.querySelector(".gallery");function h(r){const o=r.map(({webformatURL:s,largeImageURL:e,tags:t,likes:i,views:g,comments:b,downloads:L})=>`<li class="item">
        <a href="${e}"><img src="${s}" alt="${t}" /></a>
        <div class="info-box">
        <p>Likes:<span class="number">${i}</span></p>
        <p>Views:<span class="number">${g}</span></p>
        <p>Comments:<span class="number">${b}</span></p>
        <p>Downloads:<span class="number">${L}</span></p>
        </div>
      </li>`).join("");d.insertAdjacentHTML("beforeend",o),new w(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt",captionPosition:"bottom"}).refresh()}const P=document.querySelector(".search-form"),a=document.querySelector(".loader"),c=document.querySelector(".load-more");P.addEventListener("submit",v);c.addEventListener("click",$);let p="",l=1,u=15,y;a.style.display="none";c.style.display="none";async function v(r){if(r.preventDefault(),d.innerHTML="",a.style.display="block",c.style.display="none",l=1,p=r.currentTarget.searchQuery.value.trim(),p===""){a.style.display="none";return}try{const o=await f(p,l,u);l=1;const n=o.hits;n.length===0?(a.style.display="none",m.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})):(a.style.display="none",h(n),c.style.display="block",r.target.reset())}catch(o){console.log(o)}}async function $(){l+=1,a.style.display="block";try{const r=await f(p,l,u),o=r.hits,n=r.totalHits;h(o),a.style.display="none";const s=d.querySelector(".item");s&&(y=s.getBoundingClientRect().height),window.scrollBy({top:y*2,left:0,behavior:"smooth"}),l*u>=n&&(m.error({title:"Error",message:"We're sorry, but you've reached the end of search results."}),c.style.display="none")}catch(r){console.log(r)}}
//# sourceMappingURL=commonHelpers.js.map
