import{S as d,i as m}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();function y(o){const r="42024846-08e8117282465e780d398d927",s="https://pixabay.com/api/",n=new URLSearchParams({key:r,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:21});return fetch(`${s}?${n}`).then(e=>{if(!e.ok)throw new Error("error");return e.json()})}const l=document.querySelector(".gallery");function h(o){const r=o.map(({webformatURL:n,largeImageURL:e,tags:t,likes:a,views:u,comments:p,downloads:f})=>`<li class="item">
        <a href="${e}"><img src="${n}" alt="${t}" /></a>
        <div class="info-box">
        <p>Likes:<span class="number">${a}</span></p>
        <p>Views:<span class="number">${u}</span></p>
        <p>Comments:<span class="number">${p}</span></p>
        <p>Downloads:<span class="number">${f}</span></p>
        </div>
      </li>`).join("");l.insertAdjacentHTML("beforeend",r),new d(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt",captionPosition:"bottom"}).refresh()}const g=document.querySelector(".search-form"),i=document.querySelector(".loader");g.addEventListener("submit",b);let c="";i.style.display="none";function b(o){if(o.preventDefault(),l.innerHTML="",i.style.display="block",c=o.currentTarget.searchQuery.value.trim(),c===""){i.style.display="none";return}y(c).then(r=>{const s=r.hits;s.length===0?(i.style.display="none",m.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})):(i.style.display="none",h(s),o.target.reset())}).catch(r=>console.log(r))}
//# sourceMappingURL=commonHelpers.js.map
